"""Build the review site (studio/) from queue/posts.json + rendered assets.

    python3 pipeline/publish.py            # rebuild studio/data.js + media, bump ?v=
Copies assets/<media.src>/out/*.png -> studio/media/<media.src>/*.jpg (Batch 2 used bare IDs like "C1";
batch 3 onwards MUST use batch-scoped folders like "b3/C1" so IDs never collide), writes studio/data.js, stamps a cache-busting
version into index.html. Sample creatives are linked (original post URL), never re-hosted.
"""
from __future__ import annotations

import glob
import json
import os
import re
import sys
import time

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STUDIO = os.path.join(ROOT, "studio")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import taxonomy  # noqa: E402


def sample_urls() -> dict:
    try:
        return {r["id"]: r["Post URL"] for r in taxonomy.load()}
    except Exception as e:  # offline: the site still builds, sample links are just omitted
        print(f"  (taxonomy unavailable: {e}; sample links omitted)")
        return {}


def media_for(post: dict) -> dict:
    m = dict(post.get("media") or {})
    src = m.get("src")
    if m.get("type") in ("image", "carousel") and src:
        out = os.path.join(ROOT, "assets", src, "out")
        pngs = sorted(glob.glob(os.path.join(out, "slide-*.png"))) or sorted(glob.glob(os.path.join(out, "image.png")))
        if not pngs:
            return {"type": "pending"}
        dst = os.path.join(STUDIO, "media", src)
        os.makedirs(dst, exist_ok=True)
        files = []
        for i, p in enumerate(pngs, 1):
            name = f"p{i:02d}.jpg" if m["type"] == "carousel" else "image.jpg"
            im = Image.open(p).convert("RGB")
            im.save(os.path.join(dst, name), quality=90, optimize=True, progressive=True)
            files.append(f"media/{src}/{name}?v={V}")
            if m["type"] == "image":
                m["tall"] = im.height / im.width > 1.26
        m["files"] = files
    return m


def no_dashes(obj, path="") -> None:
    """Owner rule (global CLAUDE.md): no em or en dashes anywhere in published content."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            no_dashes(v, f"{path}.{k}")
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            no_dashes(v, f"{path}[{i}]")
    elif isinstance(obj, str) and re.search("[\u2013\u2014]", obj):
        raise SystemExit(f"EM/EN DASH in queue/posts.json{path}: {obj[:80]!r}")


def main() -> None:
    global V
    V = time.strftime("%Y%m%d%H%M")
    q = json.load(open(os.path.join(ROOT, "queue", "posts.json")))
    no_dashes(q)
    urls = sample_urls()
    for pr in q["profiles"]:
        pr["avatar_ok"] = os.path.exists(os.path.join(STUDIO, pr["avatar"]))
    posts = []
    for p in q["posts"]:
        p = dict(p)
        p["media"] = media_for(p)
        p["key"] = f"b{p.get('batch', '2')}-{p['id']}"
        if p.get("sample", {}).get("id") in urls:
            p["sample"]["url"] = urls[p["sample"]["id"]]
        posts.append(p)
    data = {"batches": q.get("batches", []), "profiles": q["profiles"], "posts": posts, "webinar_url": q["webinar_url"], "sync_url": q.get("sync_url", "")}
    core = {"campaigns": [], "linkChecks": [], "linkCheckedAt": "", "tokens": {}, "people": {}, "socialDefault": {"reactors": "", "comments": 0, "reposts": 0}}
    with open(os.path.join(STUDIO, "data.js"), "w") as f:
        f.write("/* generated by pipeline/publish.py from queue/posts.json - do not edit */\n")
        f.write("window.PREVIEW_DATA = " + json.dumps(core) + ";\n")
        f.write("window.STUDIO = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
    v = V
    idx = os.path.join(STUDIO, "index.html")
    html = open(idx).read()
    html = re.sub(r"\?v=[\w_]+", f"?v={v}", html)
    open(idx, "w").write(html)
    print(f"published {len(posts)} posts, v={v}")


if __name__ == "__main__":
    main()
